Release 0.13.0 changes (#78)
* CLUMIO-68025: Support building with Go 1.22 and 1.23. (#359)

Summary:
Terraform providers should be able to build with the two most recent major releases of Go.
1.23 is the current major version, 1.22 is still getting fixes and 1.21 is no longer getting security updates.

Testing: CI pipeline

Backward Compatible: Y

* CLUMIO-68025: Update dependencies to latest version (#357)

Summary:
- Update go version into 1.22
- Update direct dependencies to latest version
- Update vulnerable indirect dependencies to safe version 
  - `golang.org/x/net` -> v0.33.0
  - `golang.org/x/crypto` -> v0.31.0
- Remove constantly failed canceled context tests.

Testing: 
- [Acceptance test](https://jenkins.mcp.clum.io/job/cd/job/clumio-terraform-provider/job/terraform_acceptance_test/241/)

* CLUMIO-68616: Add MSSQL Notification in Examples (#364)

* CLUMIO-68616: Add MSSQL Notification in Examples

* CENG-5016: Refresh GitHub Actions (#368)

Summary:
Upgrade all actions to latest versions, and bump Go to v1.24.
Allow tests to run for the two most recent versions of Go.

Testing: CI pipeline.

Backward Compatible: Y

* CENG-4906: Single check target (#369)

Summary:
Allows us to have a single target branch protection rule.

Testing: CI pipeline.

Backward Compatible: Y

* CLUMIO-68446: Update protection group with documentation  (#367)

Summary:
- Upgrade SDK version and mockery
- Update the protection group document so that customer couldn’t be confused.
  - `account_native_id` will be deprecated, and customer can use `aws_account_native_id` instead.
  - Add a table for bucket rule from API documentation.
- Add a new attribute `earliest_last_modified_timestamp` in `object_filter`

Testing:
- [acceptance test](https://jenkins.mcp.clum.io/job/cd/job/clumio-terraform-provider/job/terraform_acceptance_test/250/)
- [precheckin](https://jenkins.mcp.clum.io/job/cd/job/clumio-terraform-provider/job/terraform_pre_checkin/3696/)

* Bump golang.org/x/crypto from 0.31.0 to 0.35.0 (#366)

* Bump golang.org/x/crypto from 0.31.0 to 0.35.0

Bumps [golang.org/x/crypto](https://github.com/golang/crypto) from 0.31.0 to 0.35.0.
- [Commits](https://github.com/golang/crypto/compare/v0.31.0...v0.35.0)

---
updated-dependencies:
- dependency-name: golang.org/x/crypto
  dependency-version: 0.35.0
  dependency-type: indirect
...

Signed-off-by: dependabot[bot] <support@github.com>

* .

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Dongjoo Kim <dongjoo@clumio.com>

* Fix dependabot alert (#371)

* NOJIRA: Update provider version (#372)

* NOJIRA: Update provider version

* .

* .

---------

Signed-off-by: dependabot[bot] <support@github.com>
Co-authored-by: Stephane Odul <1504511+sodul@users.noreply.github.com>
Co-authored-by: DongJoo Kim <155411162+DongJoo-clumio@users.noreply.github.com>
Co-authored-by: dependabot[bot] <49699333+dependabot[bot]@users.noreply.github.com>
Co-authored-by: Dongjoo Kim <dongjoo@clumio.com>

diff --git a/.github/workflows/test.yml b/.github/workflows/test.yml
--- a/.github/workflows/test.yml
+++ b/.github/workflows/test.yml
@@ -11,23 +11,41 @@ on:
 env:
   # This activates boringcrypto which provides FIPS compliant crypto libraries.
   GOEXPERIMENT: boringcrypto
+  # Prevent Go from downloading other versions from the Internet.
+  GOTOOLCHAIN: local
   ENABLE_TEST_REPORTS: false
+  # This should be the latest 2 major releases of Go, older versions are
+  # not maintained and lack security updates.
+  GO_LATEST: 1.24
+  GO_PREVIOUS: 1.23
 
 jobs:
+  # This prepare stage allows us to export and re-use information
+  # under the matrix strategy where `env.` resolution does not work.
+  prepare:
+    runs-on: ubuntu-latest
+    outputs:
+      go_versions: ${{ steps.go_versions.outputs.go_versions }}
+      go_latest: ${{ env.GO_LATEST }}
+    steps:
+      - name: Select Go versions
+        id: go_versions
+        run: echo "go_versions=['$GO_LATEST','$GO_PREVIOUS']" | tee -a "$GITHUB_OUTPUT"
+
   build-and-test:
     name: Build
+    needs: prepare
     strategy:
       matrix:
         os: [ ubuntu-latest, macos-latest, windows-latest ]
-        go: [ 1.21, 1.22 ]
+        go: ${{ fromJson(needs.prepare.outputs.go_versions) }}
         # Use a dynamic matrix to allow testing multiple OSes and Go versions
         # in the public repository but reduce combinations in private clones.
         exclude:
           - os: ${{ github.repository_owner == 'clumio-code' && '_' || 'macos-latest' }}
           - os: ${{ github.repository_owner == 'clumio-code' && '_' || 'windows-latest' }}
-          - go: ${{ github.repository_owner == 'clumio-code' && '_' || '1.22' }}
-            # If updating the Go version to exclude here, ensure to update the
-            # SonarCloud Scan condition below.
+          # - go: ${{ github.repository_owner == 'clumio-code' && '_' || needs.prepare.outputs.go_latest }}
+
     runs-on: ${{ matrix.os }}
     timeout-minutes: 10
     steps:
@@ -41,7 +59,7 @@ jobs:
 
     - name: Extend environment for test reports
       # When updating the Go versions in the excluded matrix, update the condition below.
-      if: github.repository_owner == 'clumio' && matrix.os == 'ubuntu-latest' && matrix.go == '1.21'
+      if: github.repository_owner == 'clumio' && matrix.os == 'ubuntu-latest' && matrix.go == env.GO_PREVIOUS
       run: |
         echo "ENABLE_TEST_REPORTS=true" >> $GITHUB_ENV
         echo "REPOSITORY_NAME=$(cut -d/ -f2 <<< ${GITHUB_REPOSITORY})" >> $GITHUB_ENV
@@ -72,9 +90,10 @@ jobs:
       timeout-minutes: 1
 
     - name: Setup gotestsum
+      # Note that `v2.0.0` is required, there is no `v2` tag for this action.
       uses: autero1/action-gotestsum@v2.0.0
       with:
-        gotestsum_version: 1.11.0
+        gotestsum_version: 1.12.1
         # https://github.com/gotestyourself/gotestsum/releases
 
     - name: Unit Tests
@@ -97,7 +116,7 @@ jobs:
 
     - name: SonarCloud Scan
       if: ${{ env.ENABLE_TEST_REPORTS == 'true' }}
-      uses: SonarSource/sonarcloud-github-action@v2
+      uses: SonarSource/sonarcloud-github-action@v5
       timeout-minutes: 5
       env:
         GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
@@ -109,3 +128,17 @@ jobs:
     - name: Check Unit Tests failure
       if: ${{ env.TEST_FAILURE == 'true' }}
       run: echo "Tests failed during the Unit Test step."; exit 1
+
+  check-build-and-test:
+    # This job checks if any of the jobs in the matrix failed.
+    # This allows us to have a single check target for the branch protection rules.
+    name: Check Build and Test
+    needs: build-and-test
+    runs-on: ubuntu-latest
+    steps:
+      - name: Check for failed jobs
+        run: |
+          if [[ "${{ needs.build-and-test.result }}" != "success" ]]; then
+            echo "One or more matrix jobs failed."
+            exit 1
+          fi
